version: '2.2'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - default
    volumes:
      - redis:/data

  web:
    build: .
    user: todo
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    networks:
      - default
    volumes:
      - .:/docker-todo
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    tmpfs:
      - /tmp

volumes:
  postgres:
    driver: local
  redis:
    driver: local
