version: '2.2'

services:
  todo-database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  todo-redis:
    image: redis
    ports:
      - "6380:6380"
    networks:
      - default
    volumes:
      - redis:/data

  todo-web:
    build: .
    user: todo
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rake assets:precompile && rake tailwindcss:build && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    networks:
      - default
    volumes:
      - .:/docker-todo
      - app-gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - todo-database
      - todo-redis
    tmpfs:
      - /tmp

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  app-gems:
    driver: local
